name: Heavy Compiler Collection
url: "https://wasted-audio.github.io/hvcc/"
theme: jekyll-theme-hacker
markdown: GFM
plugins:
  - jekyll-sitemap
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
